- config/routes.ts
- src/pages/Contacts/add.tsx
- src/pages/Contacts/demo.json
- src/services/contacts/api.ts
> add contacts page

- config/routes.ts
- package.json
- src/pages/Contacts/index.tsx
- src/pages/Demo.tsx
- src/services/contacts/api.ts
- src/services/contacts/data.ts
- src/services/demo/api.ts
- src/services/share/data.ts
> add contact table page

- src/pages/Contacts/index.tsx
> update contact page

- src/locales/en-US/pages_general.ts
- src/locales/zh-CN/pages_flow.ts
- src/locales/zh-CN/pages_general.ts
- src/locales/zh-CN/pages_process.ts
- src/pages/Flows/Components/select/drawer.tsx
- src/pages/Flows/Components/select/from.tsx
- src/pages/Flows/Components/view.tsx
- src/pages/Processes/Components/Exchange/create.tsx
- src/pages/Processes/Components/Exchange/edit.tsx
- src/pages/Processes/Components/create.tsx
- src/pages/Processes/Components/edit.tsx
> fix: update

- src/locales/en-US/pages_general.ts
- src/locales/zh-CN/pages_general.ts
- src/pages/Flows/Components/select/drawer.tsx
- src/pages/Sources/Components/create.tsx
- src/pages/Sources/Components/edit.tsx
- src/services/sources/data.ts
> Update some pages

- src/pages/Contacts/Components/create.tsx
- src/pages/Contacts/Components/edit.tsx
- src/pages/Contacts/Components/select/description.tsx
- src/pages/Flowproperties/Components/create.tsx
- src/pages/Flowproperties/Components/edit.tsx
- src/pages/Flowproperties/Components/select/description.tsx
- src/pages/Flowproperties/Components/view.tsx
- src/pages/Flows/Components/create.tsx
- src/pages/Flows/Components/edit.tsx
- src/pages/Flows/Components/model/toolbar/Exchange/index.tsx
- src/pages/Flows/Components/select/description.tsx
- src/pages/Processes/Components/Exchange/view.tsx
- src/pages/Processes/Components/create.tsx
- src/pages/Processes/Components/edit.tsx
- src/pages/Sources/Components/create.tsx
- src/pages/Sources/Components/edit.tsx
- src/pages/Sources/Components/select/description.tsx
- src/pages/Sources/Components/view.tsx
- src/pages/Unitgroups/Components/create.tsx
- src/pages/Unitgroups/Components/edit.tsx
- src/pages/Unitgroups/Components/select/description.tsx
- src/pages/Unitgroups/Components/view.tsx
- src/services/general/util.ts
Update input fields for common:timeStamp @linancn
> Update input fields for common:timeStamp

- src/components/FileViewer/gallery.tsx
- src/pages/Flowproperties/Components/select/from.tsx
- src/pages/Flows/Components/edit.tsx
- src/pages/Flows/Components/select/from.tsx
- src/pages/Processes/Components/Exchange/edit.tsx
- src/pages/Sources/Components/create.tsx
- src/pages/Sources/Components/delete.tsx
- src/pages/Sources/Components/edit.tsx
- src/pages/Sources/Components/view.tsx
- src/pages/Unitgroups/Components/select/fromMini.tsx
- src/services/general/util.ts
- src/services/sources/util.ts
- src/services/supabase/storage.ts
Update references to digital files in source components  @linancn
> Update references to digital files in source components

- config/routes.ts
- src/components/FileViewer/upload.tsx
- src/components/RightContent/AvatarDropdown.tsx
- src/locales/en-US/pages_general.ts
- src/locales/zh-CN/pages_general.ts
- src/pages/Account/password_change.tsx
- src/pages/Account/profile.tsx
- src/pages/Flowproperties/Components/create.tsx
- src/pages/Flowproperties/Components/edit.tsx
- src/pages/Flows/Components/create.tsx
- src/pages/Flows/Components/select/from.tsx
- src/pages/Processes/Components/Exchange/create.tsx
- src/pages/Unitgroups/Components/select/fromMini.tsx
> Update account menu

- src/components/LevelTextItem/description.tsx
- src/pages/Contacts/Components/view.tsx
- src/pages/Flowproperties/Components/view.tsx
- src/pages/Flows/Components/view.tsx
- src/pages/Processes/Components/view.tsx
- src/pages/Sources/Components/view.tsx
- src/pages/Unitgroups/Components/view.tsx
- src/services/contacts/api.ts
- src/services/flowproperties/api.ts
- src/services/flows/api.ts
- src/services/ilcd/api.ts
- src/services/ilcd/data.ts
- src/services/processes/api.ts
- src/services/sources/api.ts
- src/services/unitgroups/api.ts
Update ILCD classification data and API  @linancn
> Update ILCD classification data and API

- src/pages/Contacts/Components/create.tsx
- src/pages/Contacts/Components/edit.tsx
- src/pages/Contacts/Components/from.tsx
- src/services/contacts/api.ts
- src/services/contacts/util.ts
- src/services/flowproperties/api.ts
- src/services/flows/api.ts
- src/services/general/util.ts
- src/services/processes/api.ts
- src/services/sources/api.ts
- src/services/unitgroups/api.ts
Update contact form validation for Data Set Version input  @linancn
> Update contact form validation for Data Set Version input

- src/components/LangTextItem/from.tsx
- src/locales/en-US.ts
- src/locales/en-US/validator.ts
- src/locales/zh-CN.ts
- src/locales/zh-CN/validator.ts
- src/pages/Contacts/Components/form.tsx
- src/pages/Flows/Components/create.tsx
> chore: Update contact form validation for Data Set Version input

- src/components/LangTextItem/form.tsx
- src/components/LocationTextItem/description.tsx
- src/pages/Flows/Components/model/toolbar/index.tsx
- src/pages/Processes/Components/view.tsx
- src/services/demo/api.ts
- src/services/ilcd/api.ts
Update LangTextItemForm to accept rules prop  @linancn
> Update LangTextItemForm to accept rules prop

- src/components/LangTextItem/form.tsx
- src/locales/en-US/validator.ts
- src/locales/zh-CN/pages_process.ts
- src/locales/zh-CN/validator.ts
> Updated the StringMultiLang length validation.

- src/components/LocationTextItem/description.tsx
- src/components/Validator/index.tsx
- src/locales/en-US/validator.ts
- src/locales/zh-CN/validator.ts
- src/pages/Contacts/Components/form.tsx
- src/pages/Processes/Components/view.tsx
> Update the validation for the contact section.

- src/services/flows/api.ts
Update flowType for flow page @linancn
> Update flowType for flow page

- src/locales/en-US/pages_unitgroup.ts
- src/locales/zh-CN/pages_unitgroup.ts
- src/pages/Unitgroups/Components/Unit/create.tsx
- src/pages/Unitgroups/Components/Unit/edit.tsx
- src/pages/Unitgroups/Components/Unit/view.tsx
- src/pages/Unitgroups/Components/create.tsx
- src/pages/Unitgroups/Components/edit.tsx
- src/pages/Unitgroups/Components/form.tsx
- src/pages/Unitgroups/Components/select/description.tsx
- src/pages/Unitgroups/Components/select/descriptionMini.tsx
- src/pages/Unitgroups/Components/select/drawer.tsx
- src/pages/Unitgroups/Components/select/form.tsx
- src/pages/Unitgroups/Components/select/formMini.tsx
- src/pages/Unitgroups/Components/view.tsx
- src/pages/Unitgroups/index.tsx
> Refactor unit group components to improve consistency and readability

- src/locales/en-US/pages_process.ts
- src/locales/zh-CN/pages_process.ts
- src/pages/Processes/Components/Exchange/create.tsx
- src/pages/Processes/Components/Exchange/edit.tsx
- src/pages/Processes/Components/Exchange/select.tsx
- src/pages/Processes/Components/Exchange/view.tsx
- src/pages/Processes/Components/create.tsx
- src/pages/Processes/Components/edit.tsx
- src/pages/Processes/Components/form.tsx
- src/pages/Processes/Components/view.tsx
- src/pages/Processes/index.tsx
> Refactor process page components for consistency and readability

- src/components/LevelTextItem/description.tsx
- src/components/LevelTextItem/form.tsx
- src/pages/Contacts/Components/form.tsx
- src/pages/Contacts/Components/view.tsx
- src/pages/Demo.tsx
- src/pages/Flowproperties/Components/edit.tsx
- src/pages/Flowproperties/Components/form.tsx
- src/pages/Flowproperties/Components/view.tsx
- src/pages/Processes/Components/form.tsx
- src/pages/Processes/Components/view.tsx
- src/pages/Sources/Components/form.tsx
- src/pages/Sources/Components/view.tsx
- src/pages/Unitgroups/Components/form.tsx
- src/pages/Unitgroups/Components/view.tsx
- src/services/contacts/api.ts
- src/services/contacts/util.ts
- src/services/flowproperties/api.ts
- src/services/flowproperties/util.ts
- src/services/general/data.ts
- src/services/general/util.ts
- src/services/ilcd/api.ts
- src/services/ilcd/util.ts
- src/services/processes/api.ts
- src/services/processes/classification/api.ts
- src/services/processes/util.ts
- src/services/sources/api.ts
- src/services/sources/util.ts
- src/services/unitgroups/api.ts
- src/services/unitgroups/util.ts
update classification edit and view  @linancn
> update classification edit and view

- src/components/LevelTextItem/description.tsx
- src/pages/Flows/Components/form.tsx
- src/pages/Flows/Components/view.tsx
- src/services/flows/classification/api.ts
- src/services/flows/util.ts
- src/services/general/util.ts
- src/services/ilcd/api.ts
- src/services/processes/classification/api.ts
Refactor classification functions and data structure  @linancn
> Refactor classification functions and data structure

- src/components/LevelTextItem/form.tsx
- src/pages/Contacts/Components/form.tsx
- src/pages/Contacts/Components/view.tsx
- src/pages/Flowproperties/Components/form.tsx
- src/pages/Flowproperties/Components/view.tsx
- src/pages/Flows/Components/form.tsx
- src/pages/Flows/Components/view.tsx
- src/pages/Processes/Components/form.tsx
- src/pages/Processes/Components/view.tsx
- src/pages/Sources/Components/form.tsx
- src/pages/Sources/Components/view.tsx
- src/pages/Unitgroups/Components/form.tsx
- src/pages/Unitgroups/Components/view.tsx
- src/services/general/data.ts
- src/services/general/util.ts
Refactor classification form and view components  @linancn
> Refactor classification form and view components

- src/pages/LifeCycleModels/Components/toolbar/add.tsx
- src/pages/LifeCycleModels/Components/toolbar/config/node.tsx
- src/pages/LifeCycleModels/Components/toolbar/index.tsx
Refactor toolbar components and update node configuration  @linancn
> Refactor toolbar components and update node configuration

- src/locales/en-US/pages.ts
- src/locales/zh-CN/pages.ts
- src/pages/Account/index.tsx
> Added icons to the email and password fields in the account section

- src/pages/Flows/Components/select/drawer.tsx
- src/pages/Flows/index.tsx
- src/pages/LifeCycleModels/Components/toolbar/add.tsx
- src/pages/LifeCycleModels/index.tsx
- src/pages/Processes/index.tsx
- src/services/flows/api.ts
- src/services/lifeCycleModels/api.ts
- src/services/lifeCycleModels/util.ts
Refactor table rendering logic and update flow data structure  @linancn
> Refactor table rendering logic and update flow data structure

- src/locales/en-US/pages_flow.ts
- src/locales/zh-CN/pages_flow.ts
- src/pages/LifeCycleModels/Components/toolbar/index.tsx
This pull request includes changes to localization files and the toolbar component to improve the user experience by adding a new success message for saving actions.
> Refactor localization strings and add save success message

- src/locales/en-US/pages_general.ts
- src/locales/zh-CN/pages_general.ts
- src/pages/LifeCycleModels/Components/form.tsx
- src/pages/LifeCycleModels/Components/toolbar/index.tsx
- src/pages/Processes/Components/edit.tsx
- src/pages/Processes/Components/form.tsx
- src/services/flows/api.ts
- src/services/lifeCycleModels/api.ts
- src/services/lifeCycleModels/util.ts
- src/services/processes/api.ts
- src/services/processes/util.ts
Refactor life cycle model API to update process data  @linancn
> Refactor life cycle model API to update process data

- src/services/lifeCycleModels/util.ts
Refactor genProcessExchange function to handle numeric values properly  @linancn
> Refactor genProcessExchange function to handle numeric values properly

- src/services/lifeCycleModels/util.ts
Refactor genProcessTree function to handle numeric values properly  @linancn
> Refactor genProcessTree function to handle numeric values properly

- src/locales/zh-CN/pages_general.ts
- src/pages/LifeCycleModels/Components/toolbar/index.tsx
- src/services/lifeCycleModels/util.ts
Add the reference node function to the toolbar and update the relevant data processing logic  @linancn
> Add the reference node function to the toolbar and update the relevant data processing logic

- src/pages/LifeCycleModels/Components/toolbar/index.tsx
- src/services/lifeCycleModels/util.ts
Update toolbars to support quantitative reference nodes and optimize data processing logic  @linancn
> Update toolbars to support quantitative reference nodes and optimize data processing logic

- src/pages/LifeCycleModels/Components/toolbar/index.tsx
- src/pages/Processes/Components/Exchange/create.tsx
- src/pages/Processes/Components/form.tsx
- src/pages/Processes/Components/view.tsx
- src/services/processes/api.ts
Refactoring exchange data presentation, separating input and output parts, optimizing code structure  @linancn
> Refactoring exchange data presentation, separating input and output parts, optimizing code structure

- src/pages/Processes/Components/Exchange/create.tsx
- src/pages/Processes/Components/Exchange/delete.tsx
- src/pages/Processes/Components/Exchange/edit.tsx
- src/pages/Processes/Components/edit.tsx
- src/pages/Processes/Components/form.tsx
- src/services/lifeCycleModels/util.ts
Optimize the exchange component, initialize form data, remove unnecessary actionRef references, adjust input/output table references  @linancn
> Optimize the exchange component, initialize form data, remove unnecessary actionRef references, adjust input/output table references

- src/locales/en-US/pages_flow.ts
- src/locales/en-US/pages_general.ts
- src/locales/en-US/pages_model.ts
- src/locales/en-US/pages_unitgroup.ts
- src/locales/zh-CN/pages_flow.ts
- src/locales/zh-CN/pages_general.ts
- src/locales/zh-CN/pages_model.ts
- src/locales/zh-CN/pages_unitgroup.ts
- src/pages/LifeCycleModels/Components/toolbar/index.tsx
- src/pages/LifeCycleModels/Components/toolbar/targetAmount.tsx
- src/pages/Unitgroups/Components/select/descriptionMini.tsx
- src/services/lifeCycleModels/api.ts
- src/services/lifeCycleModels/util.ts
Update the processing logic for the target amount, the original amount, and the scaling factor   @linancn
> Update the processing logic for the target amount, the original amount, and the scaling factor

- src/locales/en-US/pages_general.ts
- src/locales/en-US/pages_process.ts
- src/locales/zh-CN/pages_process.ts
- src/pages/Processes/Components/form.tsx
- src/pages/Processes/Components/optiondata.tsx
- src/pages/Processes/Components/view.tsx
- src/services/processes/util.ts
This pull request introduces several changes to support the addition of workflow and publication status information in both the English and Chinese locales, as well as updates to the form and view components to handle this new information.
> Add workflow and publication status options to administrative information

- src/locales/en-US/pages_general.ts
- src/locales/zh-CN/pages_general.ts
- src/pages/LifeCycleModels/Components/toolbar/Exchange/ioPort.tsx
- src/pages/LifeCycleModels/Components/toolbar/Exchange/view.tsx
- src/pages/LifeCycleModels/Components/toolbar/index.tsx
- src/services/lifeCycleModels/util.ts
Refactoring lifecycle model data processing, adding IO port selector component   @linancn
> Refactoring lifecycle model data processing, adding IO port selector component

- src/services/lifeCycleModels/api.ts
- src/services/processes/api.ts
- src/services/processes/util.ts
Fix the name generation logic for the lifecycle model and process data  @linancn
> Fix the name generation logic for the lifecycle model and process data

- src/locales/en-US/pages_general.ts
- src/locales/zh-CN/pages_general.ts
- src/pages/LifeCycleModels/Components/create.tsx
- src/pages/LifeCycleModels/Components/delete.tsx
- src/pages/LifeCycleModels/Components/edit.tsx
- src/pages/LifeCycleModels/Components/toolbar/Exchange/index.tsx
- src/pages/LifeCycleModels/Components/toolbar/Exchange/ioPort.tsx
- src/pages/LifeCycleModels/Components/toolbar/Exchange/view.tsx
- src/pages/LifeCycleModels/Components/toolbar/add.tsx
- src/pages/LifeCycleModels/Components/toolbar/index.tsx
- src/pages/LifeCycleModels/Components/toolbar/targetAmount.tsx
- src/pages/LifeCycleModels/Components/view.tsx
- src/pages/LifeCycleModels/index.tsx
- src/pages/Processes/Components/Exchange/select.tsx
- src/pages/Processes/Components/delete.tsx
- src/pages/Processes/Components/edit.tsx
- src/pages/Processes/Components/view.tsx
- src/pages/Processes/index.tsx
- src/services/lifeCycleModels/api.ts
- src/services/processes/api.ts
- src/services/processes/data.ts
update related components to support process version  @linancn
> update related components to support process version

- src/pages/Processes/Components/edit.tsx
Optimize the ProcessEdit component  @linancn
> Optimize the ProcessEdit component

- src/components/LangTextItem/description.tsx
- src/services/processes/api.ts
Optimize property access for the LangTextItemDescription component, adding version information to the return data from the processing table  @linancn
> Optimize property access for the LangTextItemDescription component, adding version information to the return data from the processing table

- src/pages/Flows/Components/create.tsx
- src/services/flows/api.ts
- src/services/flows/util.ts
Optimized parameter passing for create flows and fixed ID reference errors when updating flows  @linancn
> Optimized parameter passing for create flows and fixed ID reference errors when updating flows

- src/components/FileViewer/gallery.tsx
- src/components/LevelTextItem/description.tsx
- src/locales/en-US/pages_general.ts
- src/locales/zh-CN/pages_general.ts
- src/pages/Contacts/Components/select/form.tsx
- src/pages/Sources/Components/create.tsx
- src/pages/Sources/Components/delete.tsx
- src/pages/Sources/Components/edit.tsx
- src/pages/Sources/Components/form.tsx
- src/pages/Sources/Components/select/description.tsx
- src/pages/Sources/Components/select/drawer.tsx
- src/pages/Sources/Components/select/form.tsx
- src/pages/Sources/Components/view.tsx
- src/pages/Sources/index.tsx
- src/services/contacts/util.ts
- src/services/flows/api.ts
- src/services/sources/api.ts
- src/services/sources/data.ts
- src/services/sources/util.ts
- src/services/supabase/storage.ts
Fixed ID passing in the create flow function  @linancn
> Fixed ID passing in the create flow function

- src/pages/Contacts/Components/select/form.tsx
- src/pages/Flowproperties/Components/create.tsx
- src/pages/Flowproperties/Components/delete.tsx
- src/pages/Flowproperties/Components/edit.tsx
- src/pages/Flowproperties/Components/form.tsx
- src/pages/Flowproperties/Components/select/description.tsx
- src/pages/Flowproperties/Components/select/drawer.tsx
- src/pages/Flowproperties/Components/select/form.tsx
- src/pages/Flowproperties/Components/view.tsx
- src/pages/Flowproperties/index.tsx
- src/pages/Flows/Components/Property/view.tsx
- src/pages/Flows/Components/form.tsx
- src/pages/Flows/Components/select/form.tsx
- src/pages/Sources/Components/select/form.tsx
- src/pages/Unitgroups/Components/select/form.tsx
- src/pages/Unitgroups/Components/select/formMini.tsx
- src/services/flowproperties/api.ts
- src/services/flowproperties/util.ts
- src/services/flows/data.ts
- src/services/flows/util.ts
Add version fields to multiple data models  @linancn
> Add version fields to multiple data models

- src/pages/LifeCycleModels/Components/create.tsx
- src/pages/LifeCycleModels/Components/edit.tsx
- src/pages/LifeCycleModels/Components/toolbar/editIndex.tsx
- src/pages/LifeCycleModels/Components/toolbar/viewIndex.tsx
- src/pages/LifeCycleModels/Components/view.tsx
- src/pages/LifeCycleModels/index.tsx
- src/pages/Processes/Components/Exchange/view.tsx
- src/pages/Processes/Components/view.tsx
- src/pages/Processes/index.tsx
- src/pages/Unitgroups/Components/Unit/reference.tsx
- src/pages/Unitgroups/Components/select/descriptionMini.tsx
- src/pages/Unitgroups/Components/select/formMini.tsx
Refactor lifecycle model components   @linancn
> Refactor lifecycle model components

- src/locales/en-US/pages_general.ts
- src/locales/zh-CN/pages_general.ts
- src/pages/Contacts/Components/create.tsx
- src/pages/Contacts/Components/edit.tsx
- src/pages/Flowproperties/Components/create.tsx
- src/pages/Flowproperties/Components/edit.tsx
- src/pages/Flows/Components/Property/create.tsx
- src/pages/Flows/Components/Property/edit.tsx
- src/pages/Flows/Components/create.tsx
- src/pages/Flows/Components/edit.tsx
- src/pages/LifeCycleModels/Components/toolbar/eidtInfo.tsx
- src/pages/LifeCycleModels/Components/toolbar/targetAmount.tsx
- src/pages/Processes/Components/Exchange/create.tsx
- src/pages/Processes/Components/Exchange/edit.tsx
- src/pages/Processes/Components/create.tsx
- src/pages/Processes/Components/edit.tsx
- src/pages/Sources/Components/create.tsx
- src/pages/Sources/Components/edit.tsx
- src/pages/Unitgroups/Components/Unit/create.tsx
- src/pages/Unitgroups/Components/Unit/edit.tsx
- src/pages/Unitgroups/Components/create.tsx
- src/pages/Unitgroups/Components/edit.tsx
Update the button text by changing "Submit" to "Save" and adding "Submit for Review" button text   @linancn
> Update the button text by changing "Submit" to "Save" and adding "Submit for Review" button text

- src/locales/en-US/pages_process.ts
- src/locales/zh-CN/pages_process.ts
- src/pages/LifeCycleModels/Components/toolbar/targetAmount.tsx
- src/pages/Processes/Components/Exchange/view.tsx
- src/pages/Processes/Components/view.tsx
- src/pages/Unitgroups/Components/select/descriptionMini.tsx
- src/services/general/util.ts
- src/services/lifeCycleModels/util.ts
- src/services/processes/data.ts
- src/services/processes/util.ts
Update the target amount calculation logic to replace the result amount with the mean   @linancn
> Update the target amount calculation logic to replace the result amount with the mean

- src/pages/LifeCycleModels/Components/toolbar/add.tsx
- src/pages/LifeCycleModels/Components/toolbar/editIndex.tsx
- src/pages/Unitgroups/Components/select/description.tsx
- src/pages/Unitgroups/Components/select/descriptionMini.tsx
- src/services/lifeCycleModels/util.ts
Fixed a calculation error in the exchange in the component  @linancn
> Fixed a calculation error in the exchange in the component

- src/pages/Contacts/Components/select/form.tsx
Optimize the contact selection form by adding criteria to set field values  @linancn
> Optimize the contact selection form

- src/services/lifeCycleModels/util.ts
Fix flow check in sumProcessExchange function  @linancn
> Fix flow check in sumProcessExchange function

- src/pages/Contacts/Components/select/drawer.tsx
- src/pages/Flowproperties/Components/select/drawer.tsx
- src/pages/Flows/Components/select/drawer.tsx
- src/pages/LifeCycleModels/Components/toolbar/add.tsx
- src/pages/LifeCycleModels/Components/toolbar/addThroughFlow.tsx
- src/pages/Sources/Components/select/drawer.tsx
- src/pages/Unitgroups/Components/select/drawer.tsx
Update the data acquisition logic   @linancn
> Update the data acquisition logic

- src/pages/Contacts/index.tsx
- src/pages/Flowproperties/index.tsx
- src/pages/Flows/index.tsx
- src/pages/LifeCycleModels/index.tsx
- src/pages/Processes/index.tsx
- src/pages/Sources/index.tsx
- src/pages/Unitgroups/index.tsx
Optimize team name processing logic  @linancn
> Optimize team name processing logic

- src/pages/Processes/Components/form.tsx
- src/pages/Processes/Components/view.tsx
- src/services/processes/util.ts
This pull request introduces several enhancements to the administrative information section in the process forms and views, as well as updates to the data processing utility functions. The changes aim to provide more detailed and structured data entry and display options.
> Add administrative information section to process form and view

- src/services/ant-design-pro/api.ts
> fix: update password field reference in changePassword function for clarity

- src/locales/zh-CN/pages_flow.ts
- src/locales/zh-CN/pages_process.ts
> fix: update reference flow terminology to '基准流' for consistency

- src/services/processes/util.ts
Simplify mapping logic in genProcessExchangeTableData function  @linancn
> fix: Simplify mapping logic in genProcessExchangeTableData function

- README.md
- README_CN.md
Update links in the documentation and correct paths to ensure proper redirection
> fix: Update links in the documentation

- src/pages/Welcome.tsx
@linancn 
feat: enhance Welcome component content with improved descriptions and headings for clarity.
> Update Welcome Page Content
